kind: Service
apiVersion: v1
metadata:
  name: fileserver
  labels:
    app: fileserver
spec:
  type: NodePort
  selector:
    app: fileserver
  ports:
  - port: 8080
    targetPort: 8080
    name: http
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: fileserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fileserver
  template:
    metadata:
      labels:
        app: fileserver
        version: v1
    spec:
      containers:
      - name: fileserver
        image: fileserver
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
